Added first implementation of bot and tests
revensif/Tinkoff_Course2024 pull request #1
Opened 2024-02-15 18:04 UTC by revensif

Команда для старта бота:
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/4bca5d26-6fa7-4d89-8c82-c82c0b7cf09b)
Команда для просмотра всех команд:
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/a46b1a05-3776-4ae0-b139-0fef60b2988c)
Команда для отслеживания ссылки (неправильно):
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/b5820000-3f33-40be-b043-b315ac14666d)
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/7b851893-97e6-43d6-861b-2248860f195a)
Команда для отслеживания ссылки (правильно):
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/35f0880a-d34b-40be-9932-0b142978cf62)
Команда для остановки отслеживания ссылки (неправильно):
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/de8ec90d-2eb7-4433-9fd5-632d9b397468)
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/644b8311-8a58-48f9-9355-54daf2ee96d8)
Команда для остановки отслеживания ссылки (правильно):
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/93045a9a-eb3c-4c3d-9e73-fca001d765c7)
Команда для просмотра всех отслеживаемых ссылок:
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/6f434891-4fe0-4a18-8ef6-2003e4540745)
Добавление меню:
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/4c581d18-97ff-4954-85d3-45573792338e)

2024-02-17 18:46 UTC, iskanred commented on bot/pom.xml
> +                        -XX:+EnableDynamicAgentLoading
question: можешь подсказать, зачем добавил флаги?

2024-02-17 18:46 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotConfig.java
> +public class BotConfig {
cofiguration классы лучше выносить в отдельный пакет

2024-02-17 23:45 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotConfig.java
> +    public DefaultBot defaultBot(ApplicationConfig config, UserMessageProcessor processor) {
можно поставить аннотацию @Component прям над классом DefaultBot . В конфигурацию обычно выносят классы, над которым нет контроля (библиотечные классы); либо для которых нужно несколько инстансов (commandManager1, commandManager2 с разными настройками)

https://www.baeldung.com/spring-component-annotation

2024-02-17 23:46 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotConfig.java
> +    public UserMessageProcessor defaultUserMessageProcessor() {
тут соответственно тоже поставить `@Component` прям над классом DefaultUserMessageProcessor

2024-02-17 23:46 UTC, iskanred commented on bot/src/main/java/edu/java/bot/DefaultBot.java
> +        bot = new TelegramBot(config.telegramToken());
style: `this` лучше указывать в конструкторе везде, где обращаешься к полям класса

2024-02-17 23:48 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/AbstractCommand.java
> +    @Override public String toString() {
тут, видимо, чето поехало, но `@Override` анноташку наверх лучше поставить)

2024-02-17 23:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/HelpCommand.java
> +        return "/help";
все строки можно вынести в static переменные в этом же классе (command, description). В других классах тоже самое

2024-02-18 00:08 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/HelpCommand.java
> +        }
тут лучше  логировани сделать в самом начале вызова, у тебя же сообщение в логе говорит, что юзер только запросил `output`, а не то, что она сейчас собирается напечататься 😁
+ в и имени лога лучше указать, юзер с каким id запросил `output`, если возможно

+ логику по объединению строк лучше вынести в отдельную приватную функцию, а то идет смешение двух типов функциональностей: техническая по объединению строк и непосредственно сама бизнес-логика метода.

то есть вот как-то:
```java
log.info("...userId...")
commands = commandsListText(processor.commands)
chatId = ...
return ...
```

2024-02-18 00:09 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/ListCommand.java
> +        long chatId = update.message().chat().id();
question: почему тут решил не логировать?

2024-02-18 00:10 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/TrackCommand.java
> +            log.info("The user requested tracking of the link");
логировать лучше в самом начале, запросил юзер в любом случае несмотря на правильность ссылки

2024-02-18 00:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/TrackCommand.java
> +            throw new RuntimeException(e);
можешь sneakyThrows попробовать

ну как минимум точно стоит хотя бы коммент оставить, почему ты бросаешь RuntimeException, а еще лучше указать в документации к методу, потому что, например, я сходу не понял)

2024-02-18 00:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/TrackCommand.java
> +        var message = update.message();
многовато кода для одного метода, попробуй попилить его на несколько, включая приватные

2024-02-18 00:20 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/DefaultUserMessageProcessor.java
> +        if (command.isPresent()) {
можешь попробовать вот это использовать https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#ifPresentOrElse(java.util.function.Consumer,java.lang.Runnable)

чтобы реализацию метода в функциональным стиле сохранить

2024-02-18 00:21 UTC, iskanred commented on bot/src/main/java/edu/java/bot/utils/Link.java
> +    @SneakyThrows @Override
анноташки лучше группировать вертикально в 95% случаев

2024-02-18 00:22 UTC, iskanred commented on bot/src/main/java/edu/java/bot/utils/LinkUtils.java
> +            && AVAILABLE_LINKS.stream().anyMatch((link) -> url.getHost().matches(link)));
тут как-то поделить по строчкам мб можно, а то строка длинная, легко запутаться в скобках

2024-02-18 00:22 UTC, iskanred commented on bot/src/main/resources/application.yml
> +  telegram-token: ${TOKEN}
✅

2024-02-18 00:26 UTC, iskanred commented on bot/src/test/java/edu/java/bot/DefaultBotTest.java
> +        assertThat(botCommands).isEqualTo(List.of(startCommand.toApiCommand()).toArray());
тяжеловавто такое читать, на будущее - тест лучше делить пробелами на три части:
1) подготовка окружения для конкретного теста (подготовка всех моков и того, что они будут возвращать)
2) вызов тестируемого метода
3) проверка результатов - сравнение actual с expected

Также рекомендую ознакомиться с `@MockBean`:
https://www.baeldung.com/java-spring-mockito-mock-mockbean

+ какую-то общую часть сетапа для всех тестов можно выносить в отдельный метод с аннотацией
`@Before*`
https://www.baeldung.com/junit-before-beforeclass-beforeeach-beforeall

2024-02-18 00:27 UTC, iskanred commented on bot/src/main/java/edu/java/bot/Bot.java
> +public interface Bot extends AutoCloseable, UpdatesListener {
самого бота и реализацию лучше вынести в сервисный слой, то есть пакет `service`

2024-02-18 00:28 UTC, iskanred commented on scrapper/src/test/java/SampleTest.java
> +        assertThat(5).isEqualTo(2 * 2 + 1);
я думаю, класс можно удалять))

2024-02-18 00:32 UTC, iskanred commented
💪 Отличная работа, здорово постарался! Видно, что хорошо понимаешь Java. Эта часть курса будет больше про Spring, поэтому придется много чего еще изучить. В целом очень грамотно выстроил архитектурно!

💯 Ставлю смело 8/8, но очень рекомендую поработать над тестами, поглубже покопать, как тестить Spring и вообще best practices в юнит и интеграционном тестировании. В будущих домашках буду на это обращать внимание.

Спасибо за скрины, кстати! 🔥

2024-02-18 12:01 UTC, revensif commented on bot/pom.xml
> +                        -XX:+EnableDynamicAgentLoading
Это вот дополнительные флаги, чтобы убрать комментарии от Mockito. Без этих флагов в консоли всегда красный текст появляется, как будто ошибка. И каждый раз проверять ошибка это или просто какие-то комментарии не очень удобно.

2024-02-18 14:34 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/Command.java
> +            && (update.message().text() != null) && (update.message().text().startsWith(command())));
кстати, тут же используется `startsWith()`

Вдруг в дальнейшем появятся команды с одинаковым префексом? Лучше развить проверку

2024-02-19 15:02 UTC, revensif commented on bot/src/main/java/edu/java/bot/processor/DefaultUserMessageProcessor.java
> +        if (command.isPresent()) {
Попытался с ifPresentOrElse, но он не подходит. Если бы не нужно было что-то возвращать, то этот вариант бы подошел.

2024-02-19 19:12 UTC, iskanred requested changes
оставил коммент

2024-02-19 19:12 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
> +    private URI getURIFromMessage(String[] messageParts) {
явное дублирование, можно подумать над тем, чтобы вынести функцию в какой-нибудь утилитарный класс для работы с сообщениями

2024-02-19 19:40 UTC, revensif commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
> +    private URI getURIFromMessage(String[] messageParts) {
Они одинаковые только временно, просто сейчас без бд их нормально не реализуешь.

2024-02-21 19:17 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
> +    private URI getURIFromMessage(String[] messageParts) {
не очень понял, почему нужна бд :/

2024-02-21 19:17 UTC, iskanred approved these changes
💯

2024-02-23 09:58 UTC, merged