completed hw7
revensif/Tinkoff_Course2024 pull request #10
Opened 2024-03-29 19:05 UTC by revensif

2024-04-15 13:18 UTC, iskanred requested changes
🔥 Задание выполнено хорошо!)

Однако следует подумать в сторну того, получится ли положиться на уже готовые реализации ретраев в reactor (webflux) клиентах.

\+ не хватило тестов на ретраи, поэтому пока 5/6. Как исправил, присылай на ревью на портале и в гитхабе. И там, и там отправил на доработку

еще вопросик по прошлым PR:
когда планируешь править/мержить PR 5 bonus? и в каком PR мне лучше проверять внесенные правки? Просто тот реквест висит с комментами, а ты вроде как и не правишь и не мержишь

p.s. прошу прощения за долгую проверку, болел и был загружен сильно две недели

2024-04-15 13:18 UTC, iskanred commented on bot/src/main/resources/application.yml
> +      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
лучше хранить под до json файла, в которрм будет ответ, а еще лучше в коде сделать объект с такими же параметрами, а не хардкодить)

2024-04-15 13:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/retry/RetryBackoffConfig.java
> +    public static class RetryExchangeFilterFunction implements ExchangeFilterFunction {
как думаешь, получилось бы, используя следующую реализацию:
https://medium.com/@robert.junklewitz/global-webclient-retry-logic-for-all-endpoints-in-spring-webflux-dbbe54206b63

![image](https://github.com/revensif/Tinkoff_Course2024/assets/37081728/c3100898-9860-43ed-b8bd-5c5e1146bfc1)

Можно использовать уже готовые `retryWhen` и создать три `ExchangeFilterFunction`, либо одну и зависеть от конфига, как сейчас. Суть в том, что реализация с константой и бэкоффом уже есть в WebFlux и их не нужно писать самим.

2024-04-15 13:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/retry/RetryBackoffConfigurationProperties.java
> +    @Value("${retry.max-attempts}") int maxAttempts,
`@Value` не нужен, если есть `@ConfigurationProperties`.

value - маппит одно поле из одного кокнкретно проперти
configurationprops - маппит целый объект с пропертями

2024-04-15 13:18 UTC, iskanred commented on bot/src/test/java/edu/java/bot/client/scrapper/DefaultHttpScrapperClientTest.java
>  public class DefaultHttpScrapperClientTest {
тестов на ретраи не хватает, хочется увидеть, что дейтсвительно при определенных ошибках запрашивается несолько раз и с задержкой определенной

2024-04-15 13:18 UTC, iskanred commented on bot/src/main/resources/application.yml
> +      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
если что, это необязательно, но было бы комфортно, советую глянуть тред:
https://stackoverflow.com/questions/69772139/spring-boot-bucket4j-customize-http-response-body-when-rate-limit-exceeds

2024-04-15 13:18 UTC, iskanred commented on scrapper/src/main/java/edu/java/dao/repository/jpa/JpaLinkRepository.java
> +    @Query("UPDATE LinkEntity SET updatedAt = :updatedAt WHERE url = :url")
без квери. неполучается чисто на нейминге?

2024-04-15 13:18 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +public class JdbcLinkUpdater implements LinkUpdater {
в итоге не стал делать единую реализацию сервисов для любых репозиториев? коммент в прошлом PR оставлял, как можно реализовать

2024-04-15 16:43 UTC, iskanred requested changes
Немного погодяя обнаружил еще один недочет реализации - все параметры для ретраев у тебя стоят для всех клиентов. Хотя разные ресурсы (бот, гитхаб, стэк) могут отвечать с разной скоростью / разными статусами / быть не доступными. В общем лучше сделать так, чтобы можно было параметризировать политику ретраев для каждого клиента.

в идеале, если еще и саму политику ретраев можно менять, например, одному ресурсу лучше linear retry, а другому - exponential или jitter

2024-04-15 16:43 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/retry/RetryBackoffConfig.java
> +    }
я бы вынес definition бинов в классы, а не методы в виде `@Component`

2024-04-15 16:43 UTC, iskanred commented on scrapper/src/main/resources/application.yml
> +  statuses: 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 520, 521, 522, 523, 524, 525, 526
как-то это странно выглядит)
мб добавить возможность указывать range статусов тоже? отдельным полем или как-то прям из этого же парсить (500-505, 500..505 или как-то еще придумать)

2024-04-15 17:26 UTC, revensif commented
> 🔥 Задание выполнено хорошо!)
> 
> Однако следует подумать в сторну того, получится ли положиться на уже готовые реализации ретраев в reactor (webflux) клиентах.
> 
> + не хватило тестов на ретраи, поэтому пока 5/6. Как исправил, присылай на ревью на портале и в гитхабе. И там, и там отправил на доработку
> 
> еще вопросик по прошлым PR: когда планируешь править/мержить PR 5 bonus? и в каком PR мне лучше проверять внесенные правки? Просто тот реквест висит с комментами, а ты вроде как и не правишь и не мержишь
> 
> p.s. прошу прощения за долгую проверку, болел и был загружен сильно две недели

Здравствуйте, у меня тоже просто завал на учебе был. Из-за того, что 4 курс, он сокращенный и тяжело время найти. Я сейчас начну исправлять бонусное и другие задания

2024-04-15 18:28 UTC, iskanred requested changes
-

2024-04-15 18:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinksService.java
> +                        response.getT1().items().getFirst().answerCount(),
что такое `T1` и `T2` из названия не очень понятно? Это Tuple из reactor?

2024-04-15 18:38 UTC, iskanred commented
> > 🔥 Задание выполнено хорошо!)
> > Однако следует подумать в сторну того, получится ли положиться на уже готовые реализации ретраев в reactor (webflux) клиентах.
> > 
> > * не хватило тестов на ретраи, поэтому пока 5/6. Как исправил, присылай на ревью на портале и в гитхабе. И там, и там отправил на доработку
> > 
> > еще вопросик по прошлым PR: когда планируешь править/мержить PR 5 bonus? и в каком PR мне лучше проверять внесенные правки? Просто тот реквест висит с комментами, а ты вроде как и не правишь и не мержишь
> > p.s. прошу прощения за долгую проверку, болел и был загружен сильно две недели
> 
> Здравствуйте, у меня тоже просто завал на учебе был. Из-за того, что 4 курс, он сокращенный и тяжело время найти. Я сейчас начну исправлять бонусное и другие задания

Понимаю) Отлично, жду правки тогда!

2024-04-16 22:22 UTC, iskanred commented
> 🔥 Задание выполнено хорошо!)
> 
> Однако следует подумать в сторну того, получится ли положиться на уже готовые реализации ретраев в reactor (webflux) клиентах. Exponential и constant точно есть готовые в WebClient. Linear можно написать свой через объект `Retry`.
> 
> + не хватило тестов на ретраи, поэтому пока 5/6. Главное протестить, что дейтсвительно код, который ты написал позволяет делать ретрай на те ошибки, которые получаешь от сервера. У нас так было на проекте, что ретраи не тестили, а в итоге спутся полгода на проде оказалось, что они и не работали, потому что ретраи триггерили напрямую на ReadTimeoutException и ConnectTimeoutException, хотя экспешены таймаутов были вложены в WebClientResponseException)) Логику лучше проверить. Особенно учитывая, что вся она у тебя сейчас кастомная и самописная.
> 
> Плюс, сейчас все параметры для ретраев у тебя стоят одни для всех клиентов. Хотя разные ресурсы (бот, гитхаб, стэк) могут отвечать с разной скоростью / разными статусами / быть не доступными. В общем лучше сделать так, чтобы можно было параметризировать политику ретраев для каждого клиента. В идеале, если еще и саму политику ретраев можно менять, например, одному ресурсу лучше linear retry, а другому - exponential или jitter. При было бы круто, если бы кол-во кода не возросло линейно. Можно иметь дефолтную родительскую реализацию политики ретраев и менять при необходимости или как-то по-другому сделать. Это необязательно, но было супер и приближенно к реальности!
> 
> В реальных проектах параметры ретраев относят к конфигу клиента:
> 
> ```yaml
> some-client:
>     base-url: ...
>     get-smth:
>         url: ${base-url}/smth/
>         ...
>      retry-policy:
>          backoff: 1s
>          backoff-type: exponential
> ```
> 
> Как исправишь, присылай на ревью на портале и в гитхабе. И там, и там отправил на доработку
> 
> Еще вопросик по прошлым PR: когда планируешь править/мержить PR 5 bonus? и в каком PR мне лучше проверять внесенные правки? Просто тот реквест висит с комментами, а ты вроде как и не правишь и не мержишь
> 
> p.s. прошу прощения за долгую проверку, болел и был загружен сильно две недели

Обновил свой комментарий, добавил контекста, чтобы было понятнее. Если остались вопросы, пиши в телеге)

2024-04-18 17:31 UTC, revensif commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinksService.java
> +                        response.getT1().items().getFirst().answerCount(),
Да это из reactor Tuple, по другому вроде это никак не написать.

2024-04-19 15:23 UTC, iskanred requested changes
🔥 Круто!
Ставлю на портале 6/6 💯

Но советы на будущее:
* Постарайся все классы делать бинами через `@Component`, когда возможно. Исключения: классы не твои (тогда понятно, что можно сделать делать конфигурацией); нужны общие условия для большой пачки бинов (как в примере с jooq, jdbc, jpa) мы вешали один `@Conditional...` на всю конфигу, вместо каждого класса, там было так удобнее
* Постарайся избегать конструкций со свитчем и выбором конкретного наследника. Пытайся придумывать общее решение с мапой + бинами. Чтобы добавляя новую реализацию (репозитория, backoff типа, и пр.) не нужно было идти и добавлять новую ветку в `if`. Так будет соблюдаться SOLID и выглядеть и будет работать с этим удобно 

В связи с этими советами, запрашиваю некоторые правки

2024-04-19 15:23 UTC, iskanred commented on bot/src/main/java/edu/java/bot/client/scrapper/DefaultHttpScrapperClient.java
> -@Component
почему удалил? лучше оставить компонентом и не выносить в конфигурации по возможности

2024-04-19 15:23 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/CommandsConfig.java
> +@Configuration
я бы команды тоже лучше вынес компонентами, нет смысла конфиг создавать в этом случае, только лишний код, не имеющий смысловой нагрузки

2024-04-19 15:23 UTC, iskanred commented on scrapper/src/main/java/edu/java/utils/RetryUtils.java
> +        }
тут можно опять же мапой заменить вместо ручной проверки)

```java
backoff-type -> Retry object
```

2024-04-19 18:22 UTC, revensif commented on scrapper/src/main/java/edu/java/utils/RetryUtils.java
> +        }
Здравствуйте, я попытался это сделать через бины. но не получается. Тут проблема в том, что надо как-то разделять ретраи. А этот не получается из-за того, что разные клиенты.

2024-04-19 18:38 UTC, revensif commented on scrapper/src/main/java/edu/java/utils/RetryUtils.java
> +        }
Когда я пытаюсь сделать бины Retry, то надо выбирать maxAttempts, delay и filter. Отсюда непонятно как выбирать, если несколько клиентов. У меня единственный вариант, который в голове появился, это сделать 3 разные мапы для бота, гита и стека. Но опять же для нового клиента придется добавлять новую мапу.

2024-04-21 23:12 UTC, iskanred commented on scrapper/src/main/java/edu/java/utils/RetryUtils.java
> +        }
Можешь попробовать сделать factory, builder или функцию вместо самого Retry

```
backoff-type -> RetryBuilder
```

```java
abstract class RetryBuilder {
    private maxAttempts;
    private delay;
    private filter;
    

    abstract Retry build()
}

abstract class LinearRetryBuilder {

    abstract LinearRetry build()
}

...
```

В общем при добавлении нового бэкофф типа не нужно менять существующий код, а просто добавить билдер класс

2024-04-21 23:17 UTC, iskanred approved these changes
Вопросик оставил и комментарий по поводу мапы. Если есть время, можешь реализовать.

В целом выглядит все хорошо, тесты добавлены, поэтому 6/6 💯

2024-04-21 23:17 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/client/github/GithubWebClientTest.java
> +        wireMockServer.verify(moreThanOrExactly(retryPolicy.maxAttempts() + 1), getRequestedFor((urlEqualTo(URL))));
почему `moreThanOrExactly`?

2024-04-22 11:13 UTC, revensif commented on scrapper/src/test/java/edu/java/scrapper/client/github/GithubWebClientTest.java
> +        wireMockServer.verify(moreThanOrExactly(retryPolicy.maxAttempts() + 1), getRequestedFor((urlEqualTo(URL))));
Иногда по какой-то причине, он не обнуляет количество запросов на определенный url. Я когда тестировал там почему-то вместо нужного количества он делал их больше.

2024-04-22 23:58 UTC, iskanred approved these changes
✅

2024-04-22 23:59 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/client/github/GithubWebClientTest.java
> +        wireMockServer.verify(moreThanOrExactly(retryPolicy.maxAttempts() + 1), getRequestedFor((urlEqualTo(URL))));
ну вообще выглядит, что надо рзазобраться, мб такое же нежелательное поведение происходии на "проде"

но это не прям важно, основноые требования соблюдены)

2024-04-27 12:02 UTC, merged