Completed hw8
revensif/Tinkoff_Course2024 pull request #12
Opened 2024-04-06 14:46 UTC by revensif

Здравствуйте, выполнил все задания, протестировать смог только с Mock. Протестировать Kafkу с TestContainer я пытался, но вышло как-то не очень поэтому я их не добавил. Но если надо могу попытаться их сделать.

2024-04-25 19:05 UTC, iskanred requested changes
Все красиво и лаконично! Очень здорово реализовал обработку ошибок в DLQ! 

Единственное, тестов на кафку не хватило)
Тестов на историю с отправкой в dlq, на консьюмеры и продюсеры

Это необязательно, если сложно и нужно поднимать кафковый тест-контейнер, но хотя бы базу, которую можно замокать надо бы прописать + поведение с DLQ увидеть все-таки хотелось бы)

Тем не менее, какие-то тесты все-таки есть + дедлайн по курсу поджимает по этому 6/6 💯

Но на гитхабе на обработку еще отправляю)

2024-04-25 19:05 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +@EnableCaching
ничего себе, где это тебе кэш понадобился)

2024-04-25 19:05 UTC, iskanred commented on bot/src/test/java/edu/java/bot/listener/ScrapperQueueListenerTest.java
> +    public void shouldListenAndSendOneUpdate() {
не хватило тестов на успешное/неуспешное поведение, когда в топик приходят плохие сообщения, чтобы потом отправились в dlq

2024-04-25 19:05 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/kafka/KafkaConfigurationProperties.java
> +    @Value("kafka.enable-idempotence") boolean enableIdempotence
тебе не нужно ставить `@Value`, когда есть аннотация `@ConfigurationProperties`!
обрати внимание, пожалуйста, не первый раз уже пишу об этом

2024-04-25 19:05 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/notification/GeneralNotificationService.java
> +        }
это, кстати, интересное решение)

оно круто, если ты хочешь переключать флаг в рантайме (и система так устроена, что она позволяет это делать), тогда новые вызовы `sendNotification` пойдут по флоу вызова другого сервиса

Но базово, когда такой флоу не предусматривается и изменение флага должно аффектить только при перезапуске, я бы рекомендовал навешивать `@Conditional...` аннотации на соответсвтующие сервисы и реализовать один интерфейс:

```java
interface BotUpdateSender { void sendUpdate() }

@ConditionalOnHavingValue("useQueue=true")
class KafkaBotUpdateSender { ... }

@ConditionalOnMissinBean(KafkaBotUpdateSender.class)
class RestBotUpdateSender { ... }

class NotificationService {
    private final BotUpdateSender botUpdateSender;
}
```

2024-04-27 13:10 UTC, revensif commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +@EnableCaching
А bucket4j разве как раз не использует кэш. Без него просто некоторые тесты не проходят. То есть по идее эта аннотация должна быть.

2024-04-30 20:07 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +@EnableCaching
действительно)

2024-04-30 20:13 UTC, iskanred approved these changes
✅

2024-05-09 13:03 UTC, merged