Completed hw9
revensif/Tinkoff_Course2024 pull request #13
Opened 2024-04-13 20:54 UTC by revensif

2024-04-30 21:08 UTC, iskanred requested changes
Вроде круто! Максимальный балл 6/6 💯

Есть коммент по поводу метрик в качестве бинов. Если в том месте, где спросил, действительно на каждое обращение создается новая метрика, то лучше самому хранить мапу таких метрик.

Я бы еще попилил бы все графики на разные панели, а то вообще ничего не понятно) Разные метрики разных типов, разные величины, размерности, промежутки, поэтмоу все на одном отображать не вариант)

Нужно, чтобы одна панель отвечала за одну метрику (хотя бы по смыслу) и обязательно метрику одного типа (counter, histogram и пр.) - т.е. либо метрика такая должна быть, либо ее надо приводить к этому

2024-04-30 21:08 UTC, iskanred commented on compose.yml
> +    volumes:
у прома еще есть data, для нее бы тоже volume сделать)

2024-04-30 21:08 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/DefaultUserMessageProcessor.java
> +            registry.counter("commands_processed_number",
вот тут он не создается каждый раз новый причем для одной и той же команды?

2024-04-30 21:08 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/DefaultUserMessageProcessor.java
> +        this.messageCounter = registry.counter("messages_processed_number");
я бы все кастомные метрики вынес в отдельные бины и просто подлкючал, куда надо

```
@Bean
Counter messageCounter() { }
```

2024-05-09 14:17 UTC, revensif commented
Здравствуйте, извините, что так долго. Последние дней 10 постоянно делал диплом, не было времени на исправление.

2024-05-23 07:48 UTC, merged