added first implementation of scrapper and tests
revensif/Tinkoff_Course2024 pull request #2
Opened 2024-02-23 16:06 UTC by revensif

2024-02-27 15:00 UTC, iskanred requested changes
🔥 Круто сделал! Рекомендую внести правки, комментарии оставил, запрос на изменения по итогам ревью тоже отправил.

💯 6/6

2024-02-27 15:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +public class ClientConfig {
Можно поставить аннотацию `@Component` над классами `GithubWebClient` `StackOverflowWebClient`, а затем использовать интерфейсы`GithubClient``StackOverflowClient`, спринг все подтянет. В конфигурации выносят бины для классов, над которыми нет контроля.

2024-02-27 15:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfig.java
> +public class SchedulerConfig {
опять же, лучше поставить `@Component` над `LinkUpdaterScheduler`, а не выносить в конигурацию

2024-02-27 15:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/stackoverflow/StackOverflowWebClient.java
> +    }
кажется, избыточно добавлять этот конструктор, `StackOverflowWebClient` в любом случае всегда будет использовать один base_url

2024-02-27 15:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/dto/stackoverflow/QuestionResponse.java
> +public record QuestionResponse(List<ItemResponse> items) {
круто рекорды используешь 🔥

2024-02-27 15:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +        log.info("Scheduler is running!");
question: проверял, работает?

2024-02-27 15:00 UTC, iskanred commented on scrapper/src/main/resources/application.yml
> +    interval: 10000
я бы или немного усложнил логику scheduluer (например, достать 10s , которые спринг преобразует в Duration автоматом, а потом из этого Duration уже получить из него миллисекунды), или хотя бы назвал `interval_ms`. Но первый вариант, конечно, предпочтительнее. Лучше тогда использовать `@ConfigurationProperties`.

```java
Duration.of(scheduler.getInterval(), ChronoUnit.SECONDS).toMillis()
 ```

2024-02-27 15:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/github/GithubWebClient.java
> +            .block();
К сожалению, пропадает смысл от использования `WebClient` при блокировке. Происходит блокировка и асинхронно уже не сможем выполнить запрос, займем поток приложения, что не очень круто.

На таком проекте в целом норм так оставить, но я бы порекомендовал не использовать `.block()`, а оставить `Mono` и в дальнейшем уже, используя реактивный подход работать с клиентами.

2024-02-27 16:31 UTC, revensif commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +public class ClientConfig {
Здравствуйте, я изначально так сделал, но по заданию просят именно через @Bean это все сделать.

2024-02-27 16:32 UTC, revensif commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +        log.info("Scheduler is running!");
Да все работает, если надо добавлю скриншот.

2024-02-28 11:26 UTC, revensif commented on scrapper/src/main/java/edu/java/client/stackoverflow/StackOverflowWebClient.java
> +    }
Справедливо, но я добавил это для того, чтобы удобно было тестировать. Иначе он бы ошибку выставлял.

2024-02-28 11:28 UTC, revensif commented
Добавил скрин работы планировщика.

![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/cab6b124-8ad3-4143-92ea-107048636c8c)

2024-02-28 17:28 UTC, iskanred requested changes
Все кайф, молодец! Одну правку запросил

2024-02-28 17:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
Лушче использовать анноташку `@NestedConfigurationProperty`

2024-02-29 21:48 UTC, iskanred approved these changes
💪

2024-03-01 11:43 UTC, merged