added first implementation of hw4 and tests
revensif/Tinkoff_Course2024 pull request #4
Opened 2024-03-08 14:00 UTC by revensif

2024-03-13 18:25 UTC, iskanred requested changes
🔥 8/8, но нужны правки

2024-03-13 18:25 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/LiquibaseSetupTest.java
> +        assertThat(true).isTrue();
а можешь как-то расширить тест?)
проверить метаданные базы или просто проверить, что инстанс постгрес контейнера запущен

у тебя не просто так  объект`POSTGRES` есть)

2024-03-13 18:25 UTC, iskanred commented on migrations/master.xml
> +    <include file="sql/chat_link.sql"/>
question: у тебя три миграции получается? мб стоит занести все в один файл, чтобы при обновлении ссылки или чата, в этом же changeSet обновлялась и chat_link?

или это один и тот же changeSet? я просто с такой конструкцией сталкиваюсь первый раз

2024-03-15 11:34 UTC, revensif commented on migrations/master.xml
> +    <include file="sql/chat_link.sql"/>
Нет получается тут 3 миграции. Я поменяю на одну. Хотя интересно, почему лучше делать все в одной?

2024-03-17 15:14 UTC, iskanred approved these changes
✅

2024-03-17 15:53 UTC, merged