Completed Hw5 bonus
revensif/Tinkoff_Course2024 pull request #6
Opened 2024-03-17 12:53 UTC by revensif

Здравствуйте, все выполнил, тесты для Jooq-сервисов не добавил. Но по идее они бы ничем не отличались кроме смены реализаций с jdbc на jooq.

2024-03-18 18:15 UTC, iskanred commented
Было бы круто отражать в PR словами сразу, какие сценарии решил добавить, чтобы мне проще было по коду проверять)

2024-03-18 18:16 UTC, iskanred commented on bot/src/main/java/edu/java/bot/utils/LinkUtils.java
>      );
вообще я бы это тоже в проперти вынес списком:
```yaml
...
resources:
  - stackoverflow\\.com
  - github\\.com
...
```

2024-03-18 19:31 UTC, iskanred requested changes
🔥 15/15 

Если смущает дублирование тестов Jooq и Jdbc, можно как-то их объединить. Допустим, оставить поля репозиториев в виде интерфейсов, а в `@SpringBootTest` аннотации уже уточнять, какие бины поднимать, или можно каждый тест параметризировать, выбирая в качестве параметра конкретную реализацию (но лучше как-то обыграть первый вариант, используя наследование или еще как-то, тут нужно подумать).

Правки как обычно, надо внести отправить на ревью)

2024-03-18 19:31 UTC, iskanred commented on bot/src/main/java/edu/java/bot/utils/LinkUtils.java
>      );
вообще я бы это тоже в проперти вынес списком:
```yaml
...
resources:
  - stackoverflow\\.com
  - github\\.com
...
```

Тогда не нужно было бы поле делать публичным и какому-то классу обращаться

2024-03-18 19:31 UTC, iskanred commented on scrapper-jooq/src/main/java/edu/java/JooqCodegen.java
> +@UtilityClass
судя по документации, не вижу смысла добавлять эту анноташку сюда:
https://projectlombok.org/features/experimental/UtilityClass

2024-03-18 19:31 UTC, iskanred commented on scrapper-jooq/src/main/java/edu/java/JooqCodegen.java
> +@SuppressWarnings("UncommentedMain")
Можно добавить excludeClasses в конфиг checkstyle:
https://checkstyle.sourceforge.io/checks/misc/uncommentedmain.html

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/github/GithubClient.java
> +    UpdatesInfo getUpdatesInfo(Link link);
давал коммент к ДЗ#5, что лучше это вынести в сервисный слой

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/stackoverflow/StackOverflowWebClient.java
> +    private static final String COMMENTS_ENDPOINT = "/questions/{id}/comments?site=stackoverflow";
такое тоже лучше выносить в проперти

может быть несколько реализацией клиента (напрмер, миграции на другой), везде объявлять переменные будет избыточно

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/stackoverflow/StackOverflowWebClient.java
> +    }
вот тут явно много логики для клиента, можно даже в отдельный сервис вынести

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +    public LinksController(@Qualifier("jdbcLinksService") LinksService linksService) {
question: без `@Qualifier` не работает?

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/stackoverflow/StackOverflowWebClient.java
> +        CommentsResponse commentsResponse = fetchComments(id).block();
не хочешь поробовать на основе `Mono` реализацию построить, не блокируясь

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/dto/stackoverflow/QuestionResponse.java
>          @JsonProperty("last_activity_date") OffsetDateTime lastActivityDate) {
jackson сам вытаскивает поля по camel или snake case с помощью [этого](https://www.baeldung.com/jackson-deserialize-snake-to-camel-case), а поля с одним словом преобразует вообще без всяких аннотаций

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/utils/LinkUtils.java
> +@UtilityClass
нужна ли тут эта аннотация тоже?

2024-03-18 19:31 UTC, iskanred commented on scrapper/src/main/java/edu/java/utils/LinkUtils.java
> +@UtilityClass
тоже лучше вынести в проперти

2024-03-20 20:03 UTC, revensif commented on scrapper-jooq/src/main/java/edu/java/JooqCodegen.java
> +@UtilityClass
Он без аннотации ругается на то, что Utils-классы не должны иметь публичных конструкторов или конструктор по умолчанию. [HideUtilityClassConstructor]

2024-03-21 02:52 UTC, iskanred commented on scrapper-jooq/src/main/java/edu/java/JooqCodegen.java
> +@UtilityClass
тогда лучше использовать как в примере по ссылке аннотацию, либо ручками закрыть консруктор

но вообще лучше максимально минимально использовать утилитарные классы в коде и выделять всю логику в сервисы

2024-03-21 02:53 UTC, iskanred commented
Еще можешь описать, как будешь разные MRы хэндлить? В оба вносить правки по очереди?)

2024-03-22 11:32 UTC, revensif commented
> Еще можешь описать, как будешь разные MRы хэндлить? В оба вносить правки по очереди?)

Думаю, что по очереди в разные напишу или исправления сразу перенесу в шестое задание, а из него буду потом закидывать в пятое и бонусное.

2024-03-25 19:16 UTC, iskanred commented
> > Еще можешь описать, как будешь разные MRы хэндлить? В оба вносить правки по очереди?)
> 
> Думаю, что по очереди в разные напишу или исправления сразу перенесу в шестое задание, а из него буду потом закидывать в пятое и бонусное.

Окей, ты получается после правок в этом PR отправить реквест на ревью? Или мне в шестое уже смотреть, а этот на PR уже все равно?

2024-03-26 08:22 UTC, revensif commented
> > > Еще можешь описать, как будешь разные MRы хэндлить? В оба вносить правки по очереди?)
> > 
> > 
> > Думаю, что по очереди в разные напишу или исправления сразу перенесу в шестое задание, а из него буду потом закидывать в пятое и бонусное.
> 
> Окей, ты получается после правок в этом PR отправить реквест на ревью? Или мне в шестое уже смотреть, а этот на PR уже все равно?

Мне кажется лучше сразу смотреть hw6 я вроде там исправил все ошибки из этого реквеста, а сюда пока закидывать не очень удобно.

2024-04-18 13:57 UTC, merged