fixed hw5
revensif/Tinkoff_Course2024 pull request #8
Opened 2024-03-17 17:37 UTC by revensif

2024-03-18 18:11 UTC, iskanred requested changes
🔥 8/8

Все здорово, хорошо проделанная работа! Есть замечания, но когда не без этого)

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/github/GithubClient.java
> +    OffsetDateTime getUpdatedAt(Link link);
`GitHubClient` это не тот уровень абстракции, на который стоит выносить это поведение. Клиент обычно соотвествует API сервиса (гитхаба). + Ко всему непонятно, что за метод, обновление чего он отдает и причем тут ссылка. Я бы вынес это в сервисный слой, где вызов используется

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/github/GithubWebClient.java
> +        RepositoryResponse response = fetchRepository(pathParts[1], pathParts[2]).block();
+тут идет блокировка, что тоже не хорошо, для этой логики будет достаточно приватной функции, которая вытащить update из репозитория 

блокировок лучше не допускать, а работать с `Mono`

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/TgChatController.java
>          return ResponseEntity.ok("Чат зарегистрирован");
можно возвращать строку, спринг сам обернет в `ResponseEntity.ok` и уйти от явного использования

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/dao/repository/jdbc/JdbcChatRepository.java
> +        return removedChat;
рекомендую ознакомиться еще с [select for update](https://ru.stackoverflow.com/questions/1064951/%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BD%D1%83%D0%B6%D0%B5%D0%BD-select-for-update), так для справки)

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/dto/Chat.java
> +public class Chat {
почему не бы не `record`?)

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +            }
мб стоит создать мапу `resource: client`, чтобы не ифать и не расширять эту конструкцию при добавлении новых ресурсов?

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/dao/repository/jdbc/JdbcChatLinkRepositoryTest.java
> +    @Rollback
если аннотация у всех методов, можно перенести на уровень класса, как правило

+вроде же она и так true по дефолту для spring test context: 
```
Rollback for integration tests in the Spring TestContext Framework defaults to true even if @Rollback is not explicitly declared.
```

https://docs.spring.io/spring-framework/reference/testing/annotations/integration-spring/annotation-rollback.html

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/dao/repository/jdbc/JdbcChatLinkRepositoryTest.java
> +@SpringBootTest
можно поднимать не весь контекст, а только те бины, которые нужны.

Например, тут не нужны бины контроллера, но они поднимуться

2024-03-18 18:11 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/service/jdbc/JdbcLinksServiceTest.java
> +    private JdbcTemplate jdbcTemplate;
можешь попробовать использовать `@MockBean` в следующий раз, чтобы не тестить все, а только сервисный слой, но это на усмотрение и зависит от тестов

https://www.baeldung.com/java-spring-mockito-mock-mockbean

2024-03-20 12:16 UTC, revensif commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +            }
Здравствуйте, так можно сделать, но проблема в том, что у них для ответов нет общего интерфейса, как и нет общего интерфейса для клиента. Я не совсем просто понимаю, как можно тогда это сделать не меняя ответ методов. И не создавая общий интерфейс для клиентов.

2024-03-20 13:25 UTC, revensif commented on scrapper/src/test/java/edu/java/scrapper/service/jdbc/JdbcLinksServiceTest.java
> +    private JdbcTemplate jdbcTemplate;
Хорошо, в следующий раз буду тестировать с помощью моков. Мне казалось, что протестировать с реальными репозиториями лучше.

2024-03-21 02:33 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/service/jdbc/JdbcLinksServiceTest.java
> +    private JdbcTemplate jdbcTemplate;
Это хорошая идея, просто это уже сервисные или интеграционные тесты, а юниты сосредоточены на одном "юните", типа репозитория)

2024-03-21 02:35 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +            }
тогда нужна какая-то абстракция поверх клиента еще, которая бы сразу хранила в себе updated at

Тут нужно подумать хорошенько, как бы не ифать)

2024-03-21 02:49 UTC, iskanred requested changes
Уже хорошо! Но обрати, пожалуйста, внимание на соблюдение принципов SOLID, особенно на O, L

Пока нужны еще правки, но уже большие успехи делаешь! Скоро будет получатся отличный код и понимание быстро построения хорошей архитектуры быстро придет) Продолжай в том же духе! 🔥

2024-03-21 02:49 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/JdbcConfig.java
> +@ConditionalOnProperty(prefix = "app", name = "database-access-type", havingValue = "jdbc")
да, крутая анноташка 🔥💪

2024-03-21 02:49 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/JdbcConfig.java
> +    @Bean
а почему снова бины объявляешь не в классе с помощью `@Component`, а конфигурацией?)

на само деле вроде понтяно, чтобы завязываться на condtitional. Но кажется, что сервисы вообще не должны зависеть от имлпементации базы. Это последний пункт SOLID - dependency inversion. Вышестоящие абстракции не должны зависеть от нижестоящих, а от интерфейсов. В общем случае все сервисы должны просто использовать интерфейсы репозиториев, а уже какая реализация будет подтягиваться (jooq или jdbc) может определяться с помощью conditional


https://habr.com/ru/articles/313796/

2024-03-21 02:49 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +                    });
можно использовать другие операторы (map, filter), их очень много, а то код сильно вложенным становитьс, а не последовательным)

я бы вынес это поведение в приватную функцию, ато что-то вложенность очень высокая и читать такое тяжело и не хочется)

2024-03-21 02:49 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +        AtomicInteger updatesCount = new AtomicInteger(0);
не очень красиво, но окей

я бы подумал, как весь этот метод можно реализовать по-другому, но это на подумать

2024-03-21 02:49 UTC, iskanred commented on scrapper/src/main/java/edu/java/utils/DatabaseAccessType.java
> +}
ой-ой, это не хорошо, когда появляются такие енамы

нужно пытаться уходить в сторону использования интерфейсов и спринг-бинов, соблюдая SOLID

2024-03-21 02:49 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/client/stackoverflow/StackOverflowWebClientTest.java
> +        client.fetchQuestion(QUESTION_ID).subscribe(response -> assertThat(response).isEqualTo(EXPECTED_RESPONSE));
в тестах можно блокироваться или использовать stepVerivier или делать join в конце

у тебя, скорее всего, поток исполнения заканчивается, посколько операция асинхронная и никаких ассертов вообще не проверяется, а тесты успешно проходят)

можешь для теста попробовать неверные ассерты вставить.

2024-03-21 02:50 UTC, iskanred commented
Если будут вопросы, заходи в телегу, подумаем вместе)

2024-03-21 08:29 UTC, revensif commented on scrapper/src/main/java/edu/java/utils/DatabaseAccessType.java
> +}
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/2874d9be-89a1-4352-b027-0877c88fc2b5)

Я так сделал потому, что так по заданию просят (в 6)

2024-03-21 13:33 UTC, revensif commented on scrapper/src/main/java/edu/java/configuration/JdbcConfig.java
> +    @Bean
![image](https://github.com/revensif/Tinkoff_Course2024/assets/70707628/05ff8ecf-49e1-419a-b649-fc3864f9c238)

Тут тоже просто по заданию делал

2024-03-21 13:47 UTC, revensif commented
Я если честно не уверен, что сделал с Mono то, что надо. Но вроде бы вариант получился рабочим и без вложенностей.

2024-03-25 19:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/utils/DatabaseAccessType.java
> +}
почему-то именно этого не видел, хорошо, спасибо!

2024-03-25 19:13 UTC, iskanred approved these changes
✅

2024-03-25 19:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +                    .subscribe();
супер! теперь еще и в основы реактивщины умеешь 🔥💪

2024-03-26 08:22 UTC, merged