Completed all tasks and added all required tests for services and repositories
revensif/Tinkoff_Course2024 pull request #9
Opened 2024-03-22 19:37 UTC by revensif

2024-03-27 20:13 UTC, iskanred requested changes
🔥 Красиво сделал!

Рекомендую архитектуру только немного перестроить, чтобы она была хорошо расширяемой - минимизация действий и рисков при добавлении: нового ресурса (github, stackoverflow, ...), новых типов репозиториев (jpa, jdbc, jooq, ...), и т.п.

Для этого всего нужно предпочитать проперти-классы хардкоженным строкам (или статическим переменным/спискам) и опираться на интерфейсы, а не на реализации. Добиться нужно того, чтобы при добавлении нового типа ресурса или репозитория, ничего не нужно было изменять в текущих классах, а было бы достаточно написать новую реализацию уже определенного интерфейса и добавить вызов этой реализации в нужном сервисе (или он уже был)
. Ну и в проперти добавить всю инфу (url, regexp, название ресурса и т.д.). Реализации dto и клиентов - само собой. Таким образом, соблюдая Open/Close принцип мы закрываем Dependency Injection принцип из SOLID.

💯 8/8

2024-03-27 20:13 UTC, iskanred commented on bot/src/main/java/edu/java/bot/utils/LinkUtils.java
> +    public static final List<String> AVAILABLE_LINKS = List.of(
го мб вынесем в проперти? Чтобы была +- единая точка добавления нового ресурса типа гитахаб или стэка:
```yaml
resources:
    github:
       base-url:
       domain:
       repo:
    stackoverlow:
      ....
```

2024-03-27 20:13 UTC, iskanred commented on bot/src/main/java/edu/java/bot/utils/LinkUtils.java
> +public final class LinkUtils {
я бы вообще расформировал этот класс.

Так как пишем на спринге, то лучше весь DI ему скормить, поэтому лучше избегать статических утилитарных классов в пользу сервисов с бизнес-логикой. Тут можно заменить на линк-валидатор и линк-парсер

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Value("${app.database-access-type}")
без этой аннотакши не получается?

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/JdbcConfig.java
> +@ConditionalOnProperty(prefix = "app", name = "database-access-type", havingValue = "jdbc")
вообще я плохо понимаю, почему в ТЗ просят енам завести, если все равно просят напрямую смотреть в проперти из конфиг-файла

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/JdbcConfig.java
> +public class JdbcConfig {
Вообще по ТЗ все правильно, но если есть желание не дублировать сервисы для каждой из реализацией, крайне рекомендую сделать сервисы независимыми от реализаций репозиториев, чтобы соблюдать принцип инверсии зависимостей из SOLID. Высокоуровневая абстракция типа сервиса не должна зависить от деталий реализации низкоуровневой типа репозитория.

Т.е. лучше сделать единые интерфейсы LinkRepository и ChatRepository, а их уже реализовывать классами типа JdbcLinkRepository, JooqLinkRepository, JpaLinkRepository и т.д.

А в сервисах уже можно полагаться только на интерфейсы репозиториев. А выбирать конкретную реализацию можно через `@Conditional...`

```java
interface MyRepository { }

interface JpaEntity...Repository extends JpaRepository<...> { }

@Repository
class JpaMyRepository implements MyRepository {
    JpaEntity...Repository jpaRepository;
    ...
}

@Repository
class JdbcMyRepository implements MyRepository {
...
}
...
```

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/dao/repository/jpa/JpaLinkRepository.java
> +    @Query("SELECT l FROM LinkEntity l WHERE l.updatedAt < :threshold")
ты везде писал квери? не пробовал без них, основываясь только на нейминге методов?

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/dao/repository/mapper/LinkRowMapper.java
> +
перенос выскочил)

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +            }
если ресурс добавится придется новую ветку ифа делать, еще и старые менять)

плюс тут не хорош получается основываться на порядке, вдруг он поменяется, т.к. наполнения листа ресурсов выходит за пределы отвественности класса

В идеале я бы сделал как-то так:
Можно вынести `checkForUpdate` в общий интерфейс `UpdateChecker`, который потом реализовать двумя сервисами `GithubUpdateChecker` и `StackoverflowUpdateChecker`.

Тогд можно мапу доменов (url -> service), которые, кстати, тоже лучше хранить в пропертях:

В общем в зависимости от домена пришедшего урла выбирать нужный `updateChecker`:
```java
domainToUpdateCheckers[url.getHost()].checkForUpdate(url);
```

Над названием переменных нужно получше подумать только)

Возможно, не апдейт чекер, а адпейт фетчер

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +            }
В общем надо постараться минимизировать изменения в существующей кодовой базе при добавлении новго ресурса, чтобы соблюдать Open/Close принцип из SOLID

Если не получится хорошего решения с мапой, надо хотя бы циклом проходится по списку ресурсов и с помощью switch-case уже определять, какой фетчер вызывать

2024-03-27 20:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinksService.java
> +@Transactional
👍

2024-04-16 19:52 UTC, revensif commented
Здравствуйте, вроде бы все переделал. Но опять почему-то build пропал. Но я проверял все нормально запускается.

2024-04-16 21:54 UTC, iskanred requested changes
правки небольшие остались)

советую с командами подумать, мб не в этом, но в PR 10й домашки реализовать)

2024-04-16 21:54 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/StartCommand.java
> +        super(processor, linkParser, messageParser);
тут, кстати, хорошо, заметно, насколько было бы полезно сделать классы команд бинами)

спринг бы сам подгружал все зависимости прям в класс, но это так, на подумать)

2024-04-16 21:54 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/LinkUpdaterFetcher.java
> +                new StackOverflowUpdateChecker(questionRepository, stackOverflowClient)
можно так не делать.

спринг сам может подгрузить в list все бины этого типа)

2024-04-16 21:54 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/LinkUpdaterFetcher.java
> +                new StackOverflowUpdateChecker(questionRepository, stackOverflowClient)
https://www.baeldung.com/spring-injecting-collections#reference

как раз так можно и команды бинами реализовать)

2024-04-17 12:41 UTC, iskanred approved these changes
Красиво и лаконично теперь! 
✅

2024-04-18 13:57 UTC, merged